# Declare your Buildkite pipelines below
---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-mcp-server-elasticsearch
  description: Buildkite Pipeline for mcp-server-elasticsearch
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/mcp-server-elasticsearch

spec:
  type: buildkite-pipeline
  owner: group:search-extract-and-transform
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: mcp-server-elasticsearch
      description: 
    spec:
      repository: elastic/mcp-server-elasticsearch
      pipeline_file: ".buildkite/pipeline.yml"
      teams:
        search-extract-and-transform:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
