# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json if available
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn install --frozen-lockfile --ignore-scripts

# Copy rest of project
COPY . .

# Build project
RUN yarn build

# Expose any ports if necessary (not strictly required for MCP over stdio)

# Start the MCP server
CMD [ "node", "dist/index.js" ]
