---
# $yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
steps:
  - label: "Check License"
    command: "npm install && npm run license-checker && npm run license-header"

  - label: "Build"
    command: "npm install && npm run build"
