name: Build Rust binaries
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to build (e.g. v0.4.1)
        required: true
        type: string

jobs:
  build-binary:
    runs-on: ${{ matrix.os.runner }}
    permissions:
      contents: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x64
          - arm64
        os:
          - name: linux
            runner: ubuntu-latest
            ext: ""
          - name: windows
            runner: windows-latest
            ext: ".exe"
          - name: macos
            runner: macos-latest
            ext: ""
    steps:
      - name: Install missing OS dependencies for Linux
        if: ${{ matrix.os.name == 'linux' && matrix.arch == 'arm64' }}
        run: sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          path: checkout-main
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ inputs.version }}
          path: checkout-tag
      - name: Get Rust target name
        id: rust-target
        env:
          RUST_OS: ${{ matrix.os.name }}
          RUST_ARCH: ${{ matrix.arch }}
        shell: bash
        run: |
          echo target=$($GITHUB_WORKSPACE/checkout-main/.github/workflows/scripts/rust-build.sh --print-target) >> "$GITHUB_OUTPUT"
      - name: Rust toolkit setup
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ steps.rust-target.outputs.target }}
      - name: Build binary ${{ matrix.os.name }}-${{ matrix.arch }}
        env:
          RUST_OS: ${{ matrix.os.name }}
          RUST_ARCH: ${{ matrix.arch }}
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE/checkout-tag
          $GITHUB_WORKSPACE/checkout-main/.github/workflows/scripts/rust-build.sh
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ inputs.version }}
          file: checkout-tag/target/${{ steps.rust-target.outputs.target }}/release/elasticsearch-core-mcp-server${{ matrix.os.ext }}
          asset_name: elasticsearch-core-mcp-server-${{ inputs.version }}-${{ matrix.os.name }}-${{ matrix.arch }}${{ matrix.os.ext }}
          overwrite: true
