name: Build Rust binaries
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to build (e.g. v0.4.1)
        required: true
        type: string

jobs:
  build-binary:
    runs-on: ${{ matrix.target.runner }}
    permissions:
      contents: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        target:
          - name: linux-x86_64
            runner: ubuntu-latest
            ext: ""
            target: x86_64-unknown-linux-gnu
          - name: windows-x86_64
            runner: windows-latest
            ext: ".exe"
            target: x86_64-pc-windows-msvc
          - name: macos-x86_64
            runner: macos-latest
            ext: ""
            target: x86_64-apple-darwin
          - name: linux-arm64
            runner: ubuntu-latest
            ext: ""
            target: aarch64-unknown-linux-gnu
          - name: windows-arm64
            runner: windows-latest
            ext: ".exe"
            target: aarch64-pc-windows-msvc
          - name: macos-arm64
            runner: macos-latest
            ext: ""
            target: aarch64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          path: checkout-main
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ inputs.version }}
          path: checkout-tag
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1.0.4
        with:
          command: build
          target: ${{ matrix.target.target }}
          args: "--locked --release"
          working-directory: ${{ github.workspace }}/checkout-tag
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ inputs.version }}
          file: checkout-tag/target/${{ matrix.target.target }}/release/elasticsearch-core-mcp-server${{ matrix.target.ext }}
          asset_name: elasticsearch-core-mcp-server-${{ inputs.version }}-${{ matrix.target.name }}${{ matrix.target.ext }}
          overwrite: true
